## Project information
site_name: Scientific writing with markdown
site_url: https://dennisangemi.github.io/md-latex-test/
site_description: È possibile scrivere in markdown report scientifici?

## Repository
repo_name: md-latex-test
repo_url: https://github.com/dennisangemi/md-latex-test
edit_uri: edit/main/docs/ #disables edit button

# Copyright
copyright: Licenza CC-BY-SA-4.0

## Social Media
extra:
## Come inserire i commenti di Disqus https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/#other-comment-systems
## Crea accont e sito shortname https://help.disqus.com/en/articles/1717111-what-s-a-shortname
## disqus: <shortname>
# disqus: ods-mkdocs-material
##  ods-mkdocs-material è lo <shortname> legato a Disqus
 social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/opendatasicilia
      name: account twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/opendatasicilia
      name: gruppo facebook
    - icon: fontawesome/brands/github
      link: https://github.com/opendatasicilia/ods-mkdocs-material
      name: Repoisitory GitHub
    - icon: fontawesome/solid/rss
      link: ../feed_rss_created.xml
      name: Feed RSS

# Configuration
theme:
  name: material
  custom_dir: overrides
  language: it
  features:
    - navigation.top
    - navigation.instant
    - navigation.tabs
    - content.code.annotate # 


  palette:
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
 # favicon:
  icon:
    repo: fontawesome/brands/github
  # logo:

plugins:
- search:
      lang: it
- mkdocstrings
- autolinks
- macros
- rss:
    abstract_chars_count: 160
    date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%d-%m-%Y"
    # datetime_format: "%Y-%m-%d"
    image:
    feed_ttl: 1440
    length: 20
    pretty_print: false
    match_path: ".*"
    url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"

markdown_extensions:
- toc:
        permalink: ↵
- meta
- mkdocs-click
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
- pymdownx.tabbed
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- pymdownx.keys
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
- attr_list
- def_list
- abbr
- pymdownx.snippets
- footnotes
- tables
- pymdownx.arithmatex:
      generic: true

## Custom theme additions
extra_javascript:
   - javascript/extra.js
   - https://unpkg.com/mermaid/dist/mermaid.min.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
   - stylesheets/extra.css


## Page tree

nav:
    - Home: index.md

    - Installazione:
        - Insta 1: Installazione/insta1.md
        - Insta 2:
            -  Insta 2.1: Installazione/insta2_1.md
            -  Insta 2.2: Installazione/insta2_2.md
        - Insta 3: Installazione/insta3.md
    - Ricette: Ricette/index.md
    - Configurazione: Configurazione/index.md
    - Riferimenti:
        - Template: Riferimenti/template.md
        - Formattazione: Riferimenti/formattazione.md
        - Strumenti: Riferimenti/strumenti.md
        - Caratteristiche: Riferimenti/caratteristiche.md
        - Rifer 1: Riferimenti/rifer1.md
        - Rifer 2:
            - Rifer 2.1: Riferimenti/rifer2_1.md
            - Rifer 2.2: Riferimenti/rifer2_2.md
            - Rifer 2.3: Riferimenti/rifer2_3a.md
    - Discussioni: 'https://github.com/opendatasicilia/ods-mkdocs-material/discussions'
    - About:
        - OpenDataSicilia: ods.md
        - Privacy: privacy.md
