## Project information
site_name: DFA - Archivio testi (test)
site_url: https://dennisangemi.github.io/mt4mkd-ltx/
site_description: È possibile scrivere in markdown report scientifici?

## Repository
repo_name: mt4mkd-ltx
repo_url: https://github.com/dennisangemi/mt4mkd-ltx
edit_uri: edit/main/docs/ #disables edit button

# Copyright
copyright: Licenza CC-BY-SA-4.0

## Social Media
extra:
 social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dennisangemi
      name: Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/dennisangemi
      name: GitHub
    - icon: fontawesome/solid/rss
      link: ../feed_rss_created.xml
      name: Feed RSS

# Configuration
theme:
  name: material
  custom_dir: overrides
  language: it
  features:
    - navigation.top
    #- navigation.instant
    - navigation.tabs
    - content.code.annotate # 


  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
 # favicon:
  icon:
    repo: fontawesome/brands/github
  # logo:

plugins:
#- pdf-export
#- mkdocstrings
#- autolinks
#- macros
- search:
      lang: it
- rss:
    abstract_chars_count: 160
    date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%d-%m-%Y"
    # datetime_format: "%Y-%m-%d"
    image:
    feed_ttl: 1440
    length: 20
    pretty_print: false
    match_path: ".*"
    url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"

markdown_extensions:
- toc:
        permalink: ↵
- meta
- md_in_html
- mkdocs-click
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
- pymdownx.tabbed
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- pymdownx.keys
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
- attr_list
- def_list
- abbr
- pymdownx.snippets
- footnotes
- tables
- pymdownx.arithmatex:
      generic: true

## Custom theme additions
extra_javascript:
   - javascript/extra.js
   - https://unpkg.com/mermaid/dist/mermaid.min.js
   - javascripts/mathjax.js
   - https://polyfill.io/v3/polyfill.min.js?features=es6
   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Foglio di stile personalizzato
extra_css:
   - stylesheets/extra.css


## Page tree

nav:
    - Home: index.md

    - Fisica 1:
        - Home: fis1/index.md
        - 2012:
           - fis1/2012/2012-01-01.md
           - fis1/2012/2012-02-01.md
        - 2013:
           - fis1/2013/2013-01-01.md
           - fis1/2013/2013-02-01.md

    - About:
        - OpenDataSicilia: ods.md
        - Privacy: privacy.md
