## Project information
site_name: DFA - Archivio testi (test)
site_url: https://dennisangemi.github.io/mt4mkd-ltx/
site_description: È possibile scrivere in markdown report scientifici?

## Repository
repo_name: mt4mkd-ltx
repo_url: https://github.com/dennisangemi/mt4mkd-ltx
edit_uri: edit/main/docs/ #disables edit button

# Copyright
copyright: Licenza CC-BY-SA-4.0

## Social Media
extra:
 social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dennisangemi
      name: Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/dennisangemi
      name: GitHub
    - icon: fontawesome/solid/rss
      link: ../feed_rss_created.xml
      name: Feed RSS

# Configuration
theme:
  name: material
  custom_dir: overrides
  language: it
  features:
    - navigation.top
    #- navigation.instant
    - navigation.tabs
    - content.code.annotate 

  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github
    logo: material/file-document-edit
   
  favicon: assets/logo_ellipse.png

plugins:
#  - tags
#  - pdf-export
#  - mkdocstrings
#  - autolinks
#  - macros
  - search:
        lang: it
  - rss:
     abstract_chars_count: 160
     date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%d-%m-%Y"
     # datetime_format: "%Y-%m-%d"
     image:
     feed_ttl: 1440
     length: 20
     pretty_print: false
     match_path: ".*"
     url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"

markdown_extensions:
- toc:
        permalink: ↵
- meta
- md_in_html
- mkdocs-click
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
- pymdownx.tabbed
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- pymdownx.keys
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
- attr_list
- def_list
- abbr
- pymdownx.snippets
- footnotes
- tables
- pymdownx.arithmatex:
      generic: true

## Custom theme additions
extra_javascript:
   - javascript/extra.js
   - https://unpkg.com/mermaid/dist/mermaid.min.js
   - javascripts/mathjax.js
   - https://polyfill.io/v3/polyfill.min.js?features=es6
   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Foglio di stile personalizzato
extra_css:
   - stylesheets/extra.css


## Page tree
nav:
    - Home: index.md

    - Fisica 1:
        - Home: fis1/index.md
        - 2009:
           - fis1/2009/yyyy-mm-dd.md
        - 2010:
           - fis1/2010/yyyy-mm-dd.md
        - 2011:
           - fis1/2011/yyyy-mm-dd.md
        - 2012:
           - fis1/2012/yyyy-mm-dd.md
        - 2013:
           - fis1/2013/2013-02-13.md
           - fis1/2013/2013-02-27.md
        - 2015:
           - fis1/2015/2015-02-11.md
           - fis1/2015/2015-07-08.md
           - fis1/2015/2015-09-09.md
           - fis1/2015/2015-12-16.md
        - 2016:
           - fis1/2016/2016-02-10.md
           - fis1/2016/2016-06-22.md
           - fis1/2016/2016-07-06.md
           - fis1/2016/2016-09-07.md
           - fis1/2016/2016-12-14.md
        - 2017:
           - fis1/2017/2017-02-08.md
           - fis1/2017/2017-02-22.md
           - fis1/2017/2017-06-21.md
           - fis1/2017/2017-07-05.md
           - fis1/2017/2017-09-06.md
           - fis1/2017/2017-12-13.md
        - 2018:
           - fis1/2018/2018-02-07.md
           - fis1/2018/2018-02-21.md
           - fis1/2018/2018-06-20.md
           - fis1/2018/2018-07-04.md
           - fis1/2018/2018-09-05.md
           - fis1/2018/2018-12-12.md
        - 2019:
           - fis1/2019/2019-02-13.md
           - fis1/2019/2019-02-27.md
           - fis1/2019/2019-06-19.md
           - fis1/2019/2019-07-03.md
           - fis1/2019/2019-09-11.md
           - fis1/2019/2019-09-25.md
           - fis1/2019/2019-12-11.md
        - 2020:
           - fis1/2020/2020-02-12.md
           - fis1/2020/2020-02-26.md
           - fis1/2020/2020-06-17.md
           - fis1/2020/2020-07-08.md
           - fis1/2020/2020-09-01.md
           - fis1/2020/2020-09-16.md
           - fis1/2020/2020-12-23.md
        - 2021:
           - fis1/2021/2021-02-03.md

    - About:
        - OpenDataSicilia: ods.md
        - Privacy: privacy.md
